# Generated by Django 4.2.2 on 2023-07-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='abc', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.CharField(default='enter text', max_length=700),
        ),
    ]
